### ISSUE TITLE
USER STORY - Site User View Profile Details

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#12]
As a **logged-in site user (employee)**, I can **view my profile details** so that **I can see the information provided during registration**.
	
### Acceptance Criteria:
- AC1: User can access a "My Profile" page.
- AC2: Profile details are displayed (name, email...).
- AC3: Information is accurate and reflects database.

### Tasks:
- [ ] Design the profile page.
- [ ] Retrieve and display user profile data (name, email...).
- [ ] Test to ensure accurate data are retrieved and displayed.
