### ISSUE TITLE
USER STORY - Admin - Manage User's Points Balance

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#13]
As a **site admin**, I can **view, add, and adjust an user’s points balance** so that **I can ensure their balance is accurate and reflects any awards or adjustments**.
	
### Acceptance Criteria:
- AC1: Admin can access each user's details from the dashboard (username and current points balance).
- AC2: Admin can adjust (increase or decrease) a user's balance as needed.
- AC3: Admin sees real-time updates or a confirmation message upon successfully modifying a balance.

### Tasks:
- [x] Implement search functionality, by employee's username.
- [x] Implement backend logic to retrieve and display user's details and current points balance.
- [x] Implement a function to adjust (increase or decrease) a user’s balance directly from the dashboard.
- [x] Test points addition or suppression with udpate in real-time.
