### ISSUE TITLE
USER STORY - Employee Logout

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#2]
As a **logged-in employee,**, I can **log out from the platform** so that **my session is ended and my data stays secure**.
	
### Acceptance Criteria:
- AC1: Employee can log out from anywhere within the platform.
- AC2: After logout, employee is redirected to the login page.
- AC3: Employee session is ended, redirecting to home page with options to Login or Register.

### Tasks:
- [x] Add a logout button, accessible from everywhere (header).
- [x] Implement backend logic to end the employee session.
- [x] Redirect employee to login page after logout.
- [x] Test logout to ensure user session and data are not accessible after logout.
