### ISSUE TITLE
USER STORY - Admin - Add New Reward

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#3]
As a **site admin**, I can **add new rewards to the catalogue** so that **I can improve the offering available to employees**.
	
### Acceptance Criteria:
- AC1: Admin can access the dashboard that displays existing rewards.
- AC2: Admin can add a new item with its details to the database.
- AC3: Required fields (name, points, description, etc...) are validated before saving.
- AC4: New reward appears in the catalogue.

### Tasks:
- [x] Determine necessary fields to create a new reward.
- [x] Save the new reward to the database and update the catalogue in real-time.
- [x] Test adding a new reward, validation, and catalogue update.
