### ISSUE TITLE
USER STORY - Admin - Edit Existing Reward

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#4]
As a **site admin**, I can **edit reward details in the data-model** so that **I can keep information current and make update as needed**.
	
### Acceptance Criteria:
- AC1: Admin can edit and modify rewards details.
- AC2: Updated information is visible to employees immediately on the platform.

### Tasks:
- [x] Allow admins to edit the rewards information from the admin dashboard.
- [x] Save the update to the database and the catalogue in real-time.
- [x] Test modifying rewards details, validation, and catalogue update.
