### ISSUE TITLE
USER STORY - Browse Available Rewards

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#6]
As a **site user (employee)**, I can **access to the list of available items** so that **I know what I can redeem my points for**.
	
### Acceptance Criteria:
- AC1: Catalogue displays all available items in a grid or list format.
- AC2: Each item shows key information at a glance (points, brand name, image).

### Tasks:
- [x] Design catalogue layout with a grid or list format.
- [x] Implement backend logic to retrieve the available items and display them in the catalogue.
- [x] Test navigation throughout the catalogue and to ensure a smooth flow and accurate information for each item.
