### ISSUE TITLE
USER STORY - Access to detailed page

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#7]
As a **site user (employee)**, I can **access the detailed page of each item** so that **I have complete information before redeeming my points**.
	
### Acceptance Criteria:
- AC1: Clicking on the item directs the user to a detailed page for the selected item.
- AC2: The detailed page displays a full description of the item, the points required, a larger image, and the terms & conditions.

### Tasks:
- [x] Design the layout for the detailed page with full description, larger image, points required, T&Cs.
- [x] Add the link or "View details" option on the catalogue page.
- [x] Implement backend logic to retrieve and display detailed information for the selected item.
- [x] Test to confirm that users can view details of the item selected and that they are accurate.
