### ISSUE TITLE
USER STORY - Add Rewards to cart

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#8]
As a **site user (employee)**, I can **add item to a cart** so that **I can review the selection before redeeming my points**.
	
### Acceptance Criteria:
- AC1: User can access to a "Add to cart" button for each item in the catalogue.
- AC2: Clicking "Add to cart" adds the item to the selection.
- AC3: If the user's point balance is insufficient, the "Add to cart" button is disabled and alert is displayed.
- AC4: User can see the total points needed in the cart.

### Tasks:
- [x] Implement a "Add to cart" button on item in the catalogue.
- [x] Display a cart icon that shows total points needed for redemption aside with points balance.
- [x] Implement backend logic to store items added to the cart for the current session.
- [x] Test the "Add to cart" button functionality for each item in the catalogue.
- [x] Verify that the cart icon updates correctly with total points displaying.
