### ISSUE TITLE
USER STORY - View Cart

### ISSUE THREAD

**Issue by SophieDufrane** [SophieDufrane/code-institute-PP4-redeemit#9]
As a **site user**, I can **view my cart** so that **I can see my selection and assess if I'm ready to redeem my points**.
	
### Acceptance Criteria:
- AC1: User can view all items added to the cart, with key details (name, points required).
- The cart displays a list of items and the total points required for all items in the cart.
- A "Redeem" button is visible.

### Tasks:
- [x] Design the cart page layout to display a list of selected items with details (name, points required).
- [x] Display the total points required for the items in the cart.
- [x] Test the cart view to verify items and total points are shown accurately
